version: "3"

services:
  webapp:
    image: prashanthdevaraj/java-docker:latest
    container_name: tomcat
    ports:
      - 8080:8080
    networks:
      - web_net
networks:
  web_net:
    driver: bridge