---
- hosts: prod-server
  become: true
  tasks:
    - name: Copy docker-compose.yml to demo server
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/
    - name: Stop running containers
      shell: docker-compose down
    - name: Pull latest docker image
      shell: docker-compose pull
    - name: Run demo app in container
      shell: docker-compose up -d

